spring:
  cloud:
    stream:
      binder:
        redis:
          default:
            backOffInitialInterval:    1000
            backOffMaxInterval:        10000
            backOffMultiplier:         2.0
            concurrency:               1
            maxAttempts:               3